name: orchestration

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.7,<3.9
  - ffmpeg==4.2.2
  - pytorch>=1.8.1
  - cudatoolkit==10.2.89
  - libsndfile>=1.0.31
  - torchaudio>=0.8
  - tqdm>=4.36
  - pip
  - pip:
    - diffq>=0.1
    - julius>=0.2.3
    - lameenc>=1.2
    - librosa>=0.8.1
    - musdb>=0.4.0
    - museval>=0.4.0
    - soundfile==0.10.3.post1
    - tensorflow
    - treetable>=0.2.3
