name: orchestration

channels:
  - pytorch
  - conda-forge

dependencies:
  - cudatoolkit>=10
  - python>=3.7,<3.9
  - ffmpeg==4.2.2
  - pytorch>=1.8.1
  - torchaudio>=0.8
  - tqdm>=4.36
  - pip
  - pip:
    - diffq>=0.1
    - julius>=0.2.3
    - lameenc>=1.2
    - librosa>=0.8.1
    - musdb>=0.4.0
    - museval>=0.4.0
    - soundfile
    - tensorflow
    - treetable>=0.2.3
